Feature/create header component
baza-trainee/remote-demining pull request #25
Opened 2023-07-17 19:30 UTC by olexanderf

2023-07-21 07:31 UTC, ViraMesha commented on components/Header/Header.tsx
> +import styles from "./Header.module.css";
Краще, щоб порядок імпортів був 

import Image from "next/image";
import { useState } from "react";

import HeaderMenu from "../HeaderMenu/HeaderMenu";
import HeaderLogo from "../HeaderLogo/HeaderLogo";
import LanguageMenu from "../LanguageMenu/LanguageMenu";
import Button from "../Button/Button";
import Container from "../Container/Container";

import styles from "./Header.module.css";

2023-07-21 07:31 UTC, ViraMesha commented on components/Header/Header.tsx
> +            <Button donateBtn={true}>Підтримати</Button>
можна просто передати donateBtn

2023-07-21 07:31 UTC, ViraMesha commented on components/HeaderLogo/HeaderLogo.module.css
> +  .logo::before {
Для стилізації це чудове рішення, але з міркувань SEO та доступності я невпевнена, що у даному випадку доцільно відображати лого як псевдоелемент. Пошукові системи та screen readers можуть не інтерпретувати вміст ::before як частину видимого контенту, що може негативно вплинути на SEO та доступність.

2023-07-21 07:31 UTC, ViraMesha commented on components/HeaderMenu/HeaderMenu.tsx
> +import styles from "./HeaderMenu.module.css";
краще поміняти імпорти місцями

2023-07-21 07:31 UTC, ViraMesha commented on components/LanguageMenu/LanguageMenu.module.css
> +.lang_option:focus,
якщо використовуваємо focus/hover, то краще прописати transition

2023-07-21 07:31 UTC, ViraMesha commented on components/LanguageMenu/LanguageMenu.module.css
> +    border: 1px solid #e3e3e3;
краще колір винесту у CSS змінну в :root

2023-07-21 07:31 UTC, ViraMesha commented on components/LanguageMenu/LanguageMenu.module.css
> +  border-top: 1px solid #e3e3e3;
краще колір винесту у CSS змінну в :root

2023-07-21 07:31 UTC, ViraMesha commented on components/LanguageMenu/LanguageMenu.module.css
> +  background-color: #e3e3e3;
краще колір винесту у CSS змінну в :root

2023-07-21 07:31 UTC, ViraMesha commented on components/LanguageMenu/LanguageMenu.module.css
> +  background-color: #e3e3e3;
краще колір винесту у CSS змінну в :root

2023-07-24 15:28 UTC, olexanderf commented on components/Header/Header.tsx
> +            <Button donateBtn={true}>Підтримати</Button>
логічно))

2023-07-24 15:34 UTC, olexanderf commented on components/LanguageMenu/LanguageMenu.module.css
> +.lang_option:focus,
додав

2023-07-24 15:37 UTC, olexanderf commented on components/LanguageMenu/LanguageMenu.module.css
> +  border-top: 1px solid #e3e3e3;
зроблено

2023-07-24 15:37 UTC, olexanderf commented on components/LanguageMenu/LanguageMenu.module.css
> +  background-color: #e3e3e3;
+

2023-07-25 07:22 UTC, ViraMesha approved these changes

2023-07-25 08:01 UTC, Black-Catt requested changes

2023-07-25 08:01 UTC, Black-Catt commented on components/Header/Header.tsx
> +import LanguageMenu from "../LanguageMenu/LanguageMenu";
Винеси ці компоненти в папку з хедером, вони ж все-таки стосуються виключно хедера

2023-07-25 14:55 UTC, olexanderf commented on components/LanguageMenu/LanguageMenu.tsx
> +  {
виніс

2023-07-25 14:55 UTC, olexanderf commented on components/Header/Header.tsx
> +import LanguageMenu from "../LanguageMenu/LanguageMenu";
Слушна думка, треба було зробити так відразу

2023-07-25 14:56 UTC, Black-Catt approved these changes

2023-07-25 14:57 UTC, merged