Add input component
baza-trainee/remote-demining pull request #4
Opened 2023-07-12 10:05 UTC by Black-Catt

2023-07-12 10:49 UTC, BigBlueDraco commented
@Black-Catt Додай будьласка скрін інпуту, так відразу видно результат/зміни

2023-07-12 11:37 UTC, Black-Catt commented
> 

![image](https://github.com/baza-trainee/remote-demining/assets/106864247/f12f78b7-2bed-4488-9815-ba3ae7d4c78e)

2023-07-13 11:14 UTC, BigBlueDraco approved these changes

2023-07-13 12:51 UTC, ItsSosha requested changes

2023-07-15 13:23 UTC, ItsSosha approved these changes

2023-07-15 13:24 UTC, merged