Feature/socrat challenges component
baza-trainee/remote-demining pull request #57
Opened 2023-07-29 15:48 UTC by olexanderf

2023-07-29 18:08 UTC, Black-Catt requested changes

2023-07-29 18:08 UTC, Black-Catt commented on components/TextCard/TextCard.tsx
> +      {title ? <h3 className={styles.title}>{title}</h3> : ""}
так буде краще `{title && <h3 className={styles.title}>{title}</h3>}`

2023-07-29 18:08 UTC, Black-Catt commented on components/SocratChallenges/SocratChallenges.tsx
А чому ти назвав SocratChallenges?( як я поняв це є просто інфа до дрона)

2023-07-29 18:24 UTC, olexanderf commented on components/TextCard/TextCard.tsx
> +      {title ? <h3 className={styles.title}>{title}</h3> : ""}
точно))

2023-07-29 18:25 UTC, olexanderf commented on components/SocratChallenges/SocratChallenges.tsx
картка в трелло була виклики) але мені здається SocratInfo краще напевно буде

2023-07-29 18:27 UTC, Black-Catt commented on components/SocratChallenges/SocratChallenges.tsx
SocratInfo буде краще а то які виклики

2023-07-29 18:30 UTC, Black-Catt approved these changes

2023-07-31 11:48 UTC, BigBlueDraco approved these changes

2023-07-31 11:48 UTC, merged