feature:add-footer-component
baza-trainee/remote-demining pull request #8
Opened 2023-07-13 18:20 UTC by betadin21

2023-07-15 08:42 UTC, ViraMesha requested changes

2023-07-15 08:42 UTC, ViraMesha commented on components/Footer/Footer.module.css
> +  padding: 70px 40px 60px 40px;
padding-top по дизайну має бути 80px і краще винести з зміну в :root

2023-07-15 08:42 UTC, ViraMesha commented on components/Footer/Footer.tsx
> +        <Link href="" className={styles.logo}>
згідно ТЗ "логотип в футері можна зробити якірною ссилкою до хедера на головній сторінці, для уникненя скролу знизу до верху". Краще уточнити цей момент у Данила

2023-07-15 08:42 UTC, ViraMesha commented on components/Footer/Footer.tsx
> +          <Link href="">
краще зробити списком: 
ul> li> Link href="">  Про нас (без тега p, просто всередині посилання помістити текст) і у нас буде перевикористовуваний компонент Navlink, який потрібно використовувати у меню

2023-07-15 08:42 UTC, ViraMesha commented on components/Footer/Footer.tsx
> +          <h4>Правила</h4>
як я зрозуміла з ТЗ, правила мають відкриватися як модальне вікно. Цитата з ТЗ "Посилання клікабельні, підкреслені як лінк, при натисканні завантажується PDF-документ з відповідною умовою.       Після прочитання документ закривається натиском на значок хрестика в верхньому правому кутку
Текст документів у PDF-форматі надає Замовник.". Я так розумію, це будуть не посилання, а кнопки (краще уточнити у Данила)

2023-07-15 08:42 UTC, ViraMesha commented on components/Footer/Footer.tsx
> +          <Link href="">
з ТЗ "Номер телефону неклікабельний, пошта клікабельна і призводить до листування."

2023-07-15 08:42 UTC, ViraMesha commented on components/Footer/Footer.tsx
> +import logo from "./icons/logo.svg";
іконки потрібно винести у кореневу папку public/icons і їх можна не імпортувати, а відразу прописувати шлях у src

2023-07-15 08:42 UTC, ViraMesha commented on components/Footer/Footer.module.css
> +  gap: 15px;
по макету gap: 8px

2023-07-15 08:42 UTC, ViraMesha commented on components/Footer/Footer.module.css
> +@media screen and (min-width: 768px) and (max-width: 1023px) {
уже є епрувнутий варіант мобілки і планшетки, перевір, будь ласка, щоб стилі відповідали макету

2023-07-25 20:27 UTC, ViraMesha requested changes

2023-07-25 20:27 UTC, ViraMesha commented on components/Footer/Footer.module.css
> +  color: rgb(50, 18, 165);
а ти впевнений, що саме такий має бути колір? У документації просто написано, що "Посиланні при наведенні курсору змінюють колір на два тони темніше." Я думаю потрібно дизайнерів попросити прописати, як виглядають посилання при ховері.

2023-07-25 20:27 UTC, ViraMesha commented on components/Footer/Footer.tsx
> +          <li className={styles.contacts__list}>
я б рекомендувала перейменувати на contacts__item, щоб назва відповідала тегу

2023-07-25 20:27 UTC, ViraMesha commented on components/Footer/Footer.tsx
> +            <Link target={"_blank"} href="">
Данило мав уточнити, чи правила будуть відкриватися у окремому вікні, бо у ТЗ вони ніби мають відображатися у модальному вікні

2023-07-27 17:16 UTC, ViraMesha approved these changes

2023-07-27 17:18 UTC, BigBlueDraco approved these changes

2023-07-27 17:18 UTC, merged