fix: footer, header and hero
baza-trainee/remote-demining pull request #85
Opened 2023-08-02 20:38 UTC by Black-Catt

![image](https://github.com/baza-trainee/remote-demining/assets/106864247/76839dd9-7ce1-44e3-ae45-53013c5644a8)
![image](https://github.com/baza-trainee/remote-demining/assets/106864247/35b2e81e-1a91-4b40-9584-7b94576d1dea)
![link](https://github.com/baza-trainee/remote-demining/assets/106864247/98608985-363a-433c-9104-0417e65164c7)

2023-08-02 21:32 UTC, ViraMesha requested changes

2023-08-02 21:32 UTC, ViraMesha commented on components/Header/HeaderMenu/HeaderMenu.tsx
> +          <NavLink href="/">Про нас</NavLink>
я думаю тут теж має бути href={'/client'}

2023-08-02 21:32 UTC, ViraMesha commented on components/Footer/Footer.tsx
> +        <div className={styles.inner}>
я думаю нам потрібно пофіксити Container і тоді не потрібно буде додавати зайвий клас. У нас у Container не прописана максимальна ширина, тому він нічого і не обмежує

2023-08-02 21:32 UTC, ViraMesha commented on components/HeroSection/HeroSection.tsx
> +    <section id="hero" className={styles.hero}>
я б тут після <section id="hero" className={styles.hero}> додала Container, але уже з пофікшеною максимальною шириною

2023-08-02 21:32 UTC, ViraMesha commented on components/NavLink/NavLink.module.css
> +  background: #000000;
по макету колір #151515 і краще використовувати CSS змінну

2023-08-02 21:38 UTC, Black-Catt commented on components/Footer/Footer.tsx
> +        <div className={styles.inner}>
Ну та я тоже так думав, але рішив шо легше створити ше один клас ніж залізти в контейнер і ше шось зламати

2023-08-02 21:38 UTC, Black-Catt commented on components/Footer/Footer.tsx
> +        <div className={styles.inner}>
Але попробую змінити його  вже завтра

2023-08-03 08:10 UTC, ViraMesha approved these changes

2023-08-03 08:10 UTC, merged